In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pip install sentence-transformers pyGithub joblib langchain torchmetrics tensorRT

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Collecting pyGithub
  Downloading pygithub-2.9.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.15)
Collecting torchmetrics
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Collecting tensorRT
  Downloading tensorrt-10.16.1.11.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Collecting pynacl>=1.4.0 (from pyGithub)
  Downloading pynacl-1.6.2-cp38-abi3-manylinux_2_34_x86_64.whl.metadata (10.0 kB)
Requirement already satisfied: requests>=2.14.0 in /usr/local/lib/python3.12/dist-packages (from pyGithub) (2.32.4)
Requirement already satisfied: pyjwt>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.4.0->pyGithub) (2.12.1)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pyGithub) (2.5.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.3.1)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: packaging>17.1 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (26.1)
Collecting lightning-utilities>=0.15.3 (from torchmetrics)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting tensorrt_cu13==10.16.1.11 (from tensorRT)
  Downloading tensorrt_cu13-10.16.1.11.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tensorrt_cu13_libs==10.16.1.11 (from tensorrt_cu13==10.16.1.11->tensorRT)
  Downloading tensorrt_cu13_libs-10.16.1.11.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tensorrt_cu13_bindings==10.16.1.11 (from tensorrt_cu13==10.16.1.11->tensorRT)
  Downloading tensorrt_cu13_bindings-10.16.1.11-cp312-none-manylinux_2_28_x86_64.whl.metadata (664 bytes)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.7.34)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (4.0.2)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (1.0.10)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.4.0->pyGithub) (43.0.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pynacl>=1.4.0->pyGithub) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.14.0->pyGithub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.14.0->pyGithub) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.14.0->pyGithub) (2026.4.22)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->pynacl>=1.4.0->pyGithub) (3.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (0.25.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Downloading pygithub-2.9.1-py3-none-any.whl (449 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.7/449.7 kB 8.9 MB/s eta 0:00:00
Downloading torchmetrics-1.9.0-py3-none-any.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 30.4 MB/s eta 0:00:00
Downloading tensorrt_cu13_bindings-10.16.1.11-cp312-none-manylinux_2_28_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 49.2 MB/s eta 0:00:00
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Downloading pynacl-1.6.2-cp38-abi3-manylinux_2_34_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 64.0 MB/s eta 0:00:00
Building wheels for collected packages: tensorRT, tensorrt_cu13, tensorrt_cu13_libs
  Building wheel for tensorRT (pyproject.toml) ... done
  Created wheel for tensorRT: filename=tensorrt-10.16.1.11-py3-none-any.whl size=16564 sha256=de62fe403bf79a318a8c580ab70cb7ead372644a31d4921593d8be6899343e50
  Stored in directory: /root/.cache/pip/wheels/9d/0c/7c/76b5862f9a4b940416c6277c77feb266b16b842f1cb26d8f9b
  Building wheel for tensorrt_cu13 (pyproject.toml) ... done
  Created wheel for tensorrt_cu13: filename=tensorrt_cu13-10.16.1.11-py3-none-any.whl size=23075 sha256=0370c3eb820cfb3212de5b6146c68c8c1b67eabb1f893fdd84d1d72e7a760ab8
  Stored in directory: /root/.cache/pip/wheels/4f/55/9a/84d81786d3b4213025298a1ed9b22cc35f1aba6d0472c619cd
  Building wheel for tensorrt_cu13_libs (pyproject.toml) ... done
  Created wheel for tensorrt_cu13_libs: filename=tensorrt_cu13_libs-10.16.1.11-py3-none-manylinux_2_28_x86_64.whl size=3728705565 sha256=91142c8ab3c58bed213cf1a563a6eb4e4f0ac529d05b5f909073acece0e3b712
  Stored in directory: /root/.cache/pip/wheels/f3/7a/3f/21ba99eefd63fdd865ce704e45311565b7985be83daaf9eecf
Successfully built tensorRT tensorrt_cu13 tensorrt_cu13_libs
Installing collected packages: tensorrt_cu13_libs, tensorrt_cu13_bindings, tensorrt_cu13, lightning-utilities, tensorRT, pynacl, torchmetrics, pyGithub
Successfully installed lightning-utilities-0.15.3 pyGithub-2.9.1 pynacl-1.6.2 tensorRT-10.16.1.11 tensorrt_cu13-10.16.1.11 tensorrt_cu13_bindings-10.16.1.11 tensorrt_cu13_libs-10.16.1.11 torchmetrics-1.9.0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
from pathlib import Path
import re
import random
from urllib.request import urlopen
from github import Github
import github
import joblib
import os
from github import GithubException
import numpy as np
from sklearn.metrics import ndcg_score
from sklearn.metrics.pairwise import cosine_similarity
from tqdm.auto import tqdm
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib
from pathlib import Path
from torchmetrics.functional import precision

In [ ]:

gh_token = """"
auth= github.Auth.Token(gh_token)
g = github.Github(auth=auth)

In [ ]:
def clean_html(text):
    text = re.sub(r"<script.*?>.*?</script>", " ", text, flags=re.DOTALL)
    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text



GITHUB_LINK_PATTERN = re.compile( rf"https://github\.com/(?P<repo>[^/]+/[^/]+)/(pull|issues)/(?P<pr>\d+)" )
COMMENT_PATTERN = re.compile(
    rf"https://github\.com/(?P<repo>[^/]+/[^/]+)/(pull|issues)/(?P<pr>\d+)#(?P<type>pullrequestreview|issuecomment)-(?P<comment_id>\d+)"
)

ANY_PATTERN = re.compile(r"https?://[^\s)>\]]+")
tag_PATTERN = re.compile(r"#(\d+)")

def scrap(url: str) -> str:
   try:
    if COMMENT_PATTERN.match(url):
        match = COMMENT_PATTERN.search(url)
        repo_name = match.group("repo")
        num = int(match.group("pr"))
        comment_id = int(match.group("comment_id"))
        repo = g.get_repo(repo_name)
        try:
            pr = repo.get_pull(num)
            return pr.get_review(comment_id).body
        except GithubException as e:
            issue = repo.get_issue(num)
            return issue.get_comment(comment_id).body

    elif GITHUB_LINK_PATTERN.match(url):
        match = GITHUB_LINK_PATTERN.search(url)
        repo_name = match.group("repo")
        num = int(match.group("pr"))
        repo = g.get_repo(repo_name)
        try:
            pr = repo.get_pull(num)
            return pr.body
        except GithubException as e:
            issue = repo.get_issue(num)
            return issue.body
    else:
        try:
            with urlopen(url) as response:
                return clean_html(response.read().decode('utf-8'))
        except Exception as e:
            # print(f"Error scraping {url}: {e}")
            return "404 no body found"
   except Exception as e:
            return "404 no body found"

In [ ]:
ds = pd.read_csv("drive/MyDrive/monnetal/lastEval/all_minilm_l6_v2.csv")
# ds = ds[~ds['pr_title'].str.contains('rollup', case=False, na=False)]
# ds = ds[ds['uid'] <= 700]

In [ ]:
import torch
import re

def extract_score_to_float(score_entry):

    if isinstance(score_entry, str):
        match = re.search(r"tensor\(\[\[(-?\d+\.?\d*(?:e[+-]\d+)?)\]\]\)", score_entry)
        if not match:
            match = re.search(r"tensor\(\[(-?\d+\.?\d*(?:e[+-]\d+)?)\]\)", score_entry)
        if match:
            return float(match.group(1))

    elif isinstance(score_entry, list) and len(score_entry) > 0 and isinstance(score_entry[0], torch.Tensor):
        return score_entry[0].item()

    return score_entry

In [ ]:
ds.drop(columns=['rerank'], inplace=True)
ds.drop(columns=['score'], inplace=True)

In [ ]:
import tqdm as notebook_tqdm

In [ ]:


import torch
import torch.nn.functional as F
torch.cuda.empty_cache()
from transformers import AutoTokenizer, BitsAndBytesConfig, RobertaConfig,AutoModel,AutoModelForSequenceClassification
import tqdm as notebook_tqdm

if using sentence-transformer embedder

In [ ]:
ds

,uid,pr_link,repo,pr_title,link_index,link,label_word,link_count,media_type,isGithub,rank,body,doc
0,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,0,https://github.com/tensorflow/tensorflow/blob/...,git_configure.bzl,4.0,NaN,NaN,1,[git_configure.bzl](https://github.com/tensorf...,tensorflow/third_party/git/git_configure.bzl a...
1,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,1,https://github.com/tensorflow/tensorflow/blob/...,tools/git/gen_git_source.py,4.0,NaN,NaN,2,[git_configure.bzl](https://github.com/tensorf...,tensorflow/tensorflow/tools/git/gen_git_source...
2,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,2,https://github.com/tensorflow/tensorflow/commi...,https://github.com/tensorflow/tensorflow/commi...,4.0,NaN,NaN,3,[git_configure.bzl](https://github.com/tensorf...,PY3 Migration - //tensorflow/tools [2] · tenso...
3,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,3,https://github.com/tensorflow/tensorflow/blob/...,https://github.com/tensorflow/tensorflow/blob/...,4.0,NaN,NaN,4,[git_configure.bzl](https://github.com/tensorf...,tensorflow/tensorflow/tools/git/gen_git_source...
4,25,https://github.com/pytorch/pytorch/pull/60755,pytorch/pytorch,"[cuDNN v8 API] cuDNN benchmark, convolution bw...",0,https://github.com/pytorch/pytorch/issues/58414,#58414,5.0,NaN,NaN,1,"#58414, #58859, #58858 #58860 #58861\r\n\r\nWe...","cuDNN v8 introduces a completely new API, and ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,494,https://github.com/flutter/flutter/pull/73154,flutter/flutter,Roll Engine from 7cb464aedbf3 to 82b4ae86d69b ...,7,https://skia.googlesource.com/buildbot/+doc/ma...,https://skia.googlesource.com/buildbot/+doc/ma...,8.0,NaN,NaN,7,\nhttps://github.com/flutter/engine/compare/7c...,AutoRoll AutoRoll AutoRoll is a program which ...
352,498,https://github.com/godotengine/godot/pull/56931,godotengine/godot,Enforce mult-of-4 requirements on etcpak input.,0,https://github.com/godotengine/godot/issues/49981,#49981,4.0,NaN,NaN,2,Re: https://github.com/godotengine/godot/issue...,### Godot version\n\neb318d3e04ac6d3bb01b0f2a8...
353,498,https://github.com/godotengine/godot/pull/56931,godotengine/godot,Enforce mult-of-4 requirements on etcpak input.,1,https://github.com/godotengine/godot/pull/4737...,#47370,4.0,NaN,NaN,1,Re: https://github.com/godotengine/godot/issue...,**Add `etcpak` library for faster ETC/ETC2/S3T...
354,498,https://github.com/godotengine/godot/pull/56931,godotengine/godot,Enforce mult-of-4 requirements on etcpak input.,2,https://github.com/godotengine/godot/commit/74...,"added by reduz in February, 2019",4.0,NaN,NaN,4,Re: https://github.com/godotengine/godot/issue...,Many separate fixes to ensure non power of 2 t...
355,498,https://github.com/godotengine/godot/pull/56931,godotengine/godot,Enforce mult-of-4 requirements on etcpak input.,3,https://github.com/godotengine/godot/issues/49981,#49981,4.0,NaN,NaN,3,Re: https://github.com/godotengine/godot/issue...,### Godot version\n\neb318d3e04ac6d3bb01b0f2a8...

In [ ]:
from transformers import AutoModel

model = AutoModel.from_pretrained(
    'jinaai/jina-reranker-v3',
    trust_remote_code=True,
)

model.eval()
model = model.to("cuda")

if hasattr(model, 'config'):
    model.config.use_cache = True
# model = torch.compile(model, mode="max-autotune")

Loading weights:   0%|          | 0/312 [00:00<?, ?it/s]

In [ ]:
# @title
import tqdm
ds['score'] = None
pass_uid = None
pr_num = None
repo = None
pr = None
body = None
body_vec = None
link_bodies = []
itr = 0
i_start = 0
print(model)
for i in tqdm.auto.tqdm(ds.index, desc="Re-ranking PR links"):
    # if ds.loc[i, "uid"] < 686:
      # continue

    # torch.cuda.empty_cache()

    # pr_name = ds.loc[i, "repo"]
    # pr_link = ds.loc[i, "pr_link"]

    if pass_uid != ds.loc[i, "uid"]:
      i_start = i
      # pr_num = int(GITHUB_LINK_PATTERN.search(pr_link).group("pr"))
      # repo = g.get_repo(pr_name)
      # pr = repo.get_pull(pr_num)
      body = ds.loc[i,"body"] or ""
      # body = pr.body or ""
      # ds.loc[i, "body"] = body

    # doc_url = ds.loc[i, "link"]
    # doc = scrap(doc_url)
    # ds.loc[i, "doc"] = doc
    doc = ds.loc[i,"doc"] or ""
    link_bodies.append(str(doc))
    next_uid = ds.loc[i+1, "uid"] if i+1 in ds.index else None
    if next_uid != ds.loc[i, "uid"]:
        # for item in link_bodies:
          # print(f"{type(item)}")
      scores = model.rerank(body,link_bodies)

      for j, s in enumerate(scores):
        ds.at[i_start + j, "score"] = s['relevance_score']
      # ds.loc[i_start:i_start + len(scores) - 1, "score"] = scores

    pass_uid = ds.loc[i, "uid"]

ds['rerank'] = (
    ds
    .groupby("pr_link")['score']
    .rank(method="first", ascending=False)
    .astype("Int64")
)


out  = f"drive/MyDrive/monnetal/fold8/jina_reranker.csv"
ds['body'].fillna(method='ffill', inplace=True)
ds.to_csv(out, index=False)

print(f"Saved new evaluation to {out}")

JinaForRanking(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 1024)
    (layers): ModuleList(
      (0-27): 28 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=1024, out_features=2048, bias=False)
          (k_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (o_proj): Linear(in_features=2048, out_features=1024, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (up_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (down_proj): Linear(in_features=3072, out_features=1024, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((1024,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=1024, out_features=151936, bias=False)
  (projector): Sequential(
    (0): Linear(in_features=1024, out_features=512, bias=False)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=False)
  )
)

Re-ranking PR links:   0%|          | 0/356 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

Saved new evaluation to drive/MyDrive/monnetal/fold8/jina_reranker.csv

/tmp/ipykernel_536/1850408087.py:58: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['body'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_536/1850408087.py:58: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ds['body'].fillna(method='ffill', inplace=True)

In [ ]:
ds.loc[190, 'doc'] = " "

In [ ]:
ds['score'] = 0.0  # Default all scores to 0

for i in tqdm(ds.index[:10], desc="Safe processing"):  # Test first 10 only
    try:
        body = "test body"  # Use simple test strings
        doc = "test document"
        score = model.predict([["test body", "test document"]])[0]
        ds.at[i, "score"] = score
    except:
        ds.at[i, "score"] = 0.0

Safe processing:   0%|          | 0/10 [00:00<?, ?it/s]

In [ ]:
# @title

print("Loading sentence transformers...")

model_name = "sentence-transformers/all-MiniLM-L6-v2"
save_name = model_name.replace("/", "_")
from sentence_transformers import CrossEncoder, SentenceTransformer
attn_implementation = "eager"
model = SentenceTransformer(
    model_name,
    # trust_remote_code=True,
    # model_kwargs={"attn_implementation": attn_implementation, "dtype": "bfloat16"},
    # tokenizer_kwargs={"padding_side": "left"},
)

print("Model loaded")

Loading sentence transformers...

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model loaded

In [ ]:
# @title
ds['score'] = None
ds['rerank'] = None
eval_results = []
for i in tqdm(range(len(ds)), desc="Processing PRs"):


    pr_name = ds.loc[i, "repo"]
    pr_link = ds.loc[i, "pr_link"]
    pr_num = int(GITHUB_LINK_PATTERN.search(pr_link).group("pr"))
    repo = g.get_repo(pr_name)
    pr = repo.get_pull(pr_num)
    body = pr.body
    # print(f'{i} body: {body[20:]}')
    # body = ds.iloc[i]["body"]
    ds.loc[i, "body"] = body or " "
    body_vec = model.encode_query(body)
    doc = ""
    try:
            doc = scrap(ds.loc[i,'link'])
            ds.loc[i, "doc"] = doc or " "
            # doc = ds.iloc[i]["doc"]
            # print(f'{i} doc: {doc[20:]}')
            doc_vec = model.encode_query(doc)
            score = model.similarity(body_vec, doc_vec)
            ds.loc[i, 'score'] = score
            print(score)

    except Exception as e:
            ds.loc[i,'score'] = -999
            continue

ds['rerank'] = (
    ds
    .groupby("pr_link")['score']
    .rank(method="first", ascending=False)
    .astype("Int64")
)

ds['score'] = ds['score'].apply(extract_score_to_float)
ds.to_csv(f"drive/MyDrive/monnetal/lastEval/all_minilm_l6_v2.csv", index=False)

Processing PRs:   0%|          | 0/356 [00:00<?, ?it/s]

tensor([[0.4090]])
tensor([[0.4175]])
tensor([[0.4260]])
tensor([[0.4175]])
tensor([[0.7360]])
tensor([[0.1312]])
tensor([[0.1312]])
tensor([[0.1312]])
tensor([[0.1312]])
tensor([[0.0245]])
tensor([[0.0245]])
tensor([[0.1507]])
tensor([[0.0245]])
tensor([[0.0245]])
tensor([[0.0231]])
tensor([[0.0245]])
tensor([[0.2764]])
tensor([[0.7860]])
tensor([[0.8140]])
tensor([[0.8773]])
tensor([[0.2366]])
tensor([[-0.0148]])
tensor([[1.0000]])
tensor([[0.4607]])
tensor([[0.4354]])
tensor([[0.4849]])
tensor([[0.4415]])
tensor([[0.4274]])
tensor([[0.3016]])
tensor([[0.4491]])
tensor([[0.3589]])
tensor([[0.1977]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.0739]])
tensor([[0.5620]])
tensor([[0.7897]])
tensor([[0.5779]])
tensor([[-0.0403]])
tensor([[0.3828]])
tensor([[0.5092]])
tensor([[0.2148]])
tensor([[0.4770]])
tensor([[0.3098]])
tensor([[0.3200]])
tensor([[0.3200]])
tensor([[0.1978]])
tensor([[0.0859]])
tensor([[0.5770]])
tensor([[0.2883]])
tensor([[0.2883]])
tensor([[0.1594]])
tensor([[0.2078]])
tensor([[0.0323]])
tensor([[0.0207]])
tensor([[0.0207]])
tensor([[0.0812]])
tensor([[0.4921]])
tensor([[0.6107]])
tensor([[1.0000]])
tensor([[0.6375]])
tensor([[0.6407]])
tensor([[0.0247]])
tensor([[0.0369]])
tensor([[0.6406]])
tensor([[1.]])
tensor([[-0.0185]])
tensor([[0.4121]])
tensor([[1.0000]])
tensor([[0.6039]])
tensor([[0.8966]])
tensor([[0.2722]])
tensor([[0.8986]])
tensor([[0.9039]])
tensor([[0.7783]])
tensor([[1.0000]])
tensor([[0.4448]])
tensor([[1.0000]])
tensor([[0.8133]])
tensor([[0.1291]])
tensor([[0.7720]])
tensor([[0.5986]])
tensor([[0.5782]])
tensor([[0.5955]])
tensor([[0.0683]])
tensor([[0.0052]])
tensor([[0.6315]])
tensor([[0.5626]])
tensor([[0.5969]])
tensor([[0.6663]])
tensor([[0.6190]])
tensor([[0.5278]])
tensor([[0.3287]])
tensor([[0.5838]])
tensor([[0.3767]])
tensor([[0.0709]])
tensor([[0.2994]])
tensor([[0.5906]])
tensor([[0.5906]])
tensor([[0.1669]])
tensor([[0.6905]])
tensor([[0.5209]])
tensor([[0.7123]])
tensor([[0.5815]])
tensor([[0.6971]])
tensor([[0.6245]])
tensor([[0.4283]])
tensor([[0.5260]])
tensor([[0.6434]])
tensor([[0.7075]])
tensor([[0.5680]])
tensor([[0.3198]])
tensor([[0.1005]])
tensor([[0.4824]])
tensor([[0.1005]])
tensor([[0.3115]])
tensor([[0.1005]])
tensor([[0.2660]])
tensor([[0.5249]])
tensor([[0.5249]])
tensor([[0.2823]])
tensor([[0.1603]])
tensor([[0.2398]])
tensor([[0.1603]])
tensor([[0.2398]])
tensor([[0.1603]])
tensor([[0.1754]])
tensor([[0.2398]])
tensor([[0.8097]])
tensor([[0.8097]])
tensor([[0.4851]])
tensor([[0.5617]])
tensor([[0.0863]])
tensor([[0.3327]])
tensor([[0.8525]])
tensor([[0.5086]])
tensor([[0.0028]])
tensor([[-0.0183]])
tensor([[0.6311]])
tensor([[0.2298]])
tensor([[0.5189]])
tensor([[0.3470]])
tensor([[0.3635]])
tensor([[0.1121]])
tensor([[0.2922]])
tensor([[0.4356]])
tensor([[0.5233]])
tensor([[0.3776]])
tensor([[0.4016]])
tensor([[0.2597]])
tensor([[0.3203]])
tensor([[0.2100]])
tensor([[0.2271]])
tensor([[0.1872]])
tensor([[1.]])
tensor([[-0.0391]])
tensor([[0.1130]])
tensor([[0.1996]])
tensor([[0.1996]])
tensor([[-0.0622]])
tensor([[-0.0622]])
tensor([[0.3791]])
tensor([[0.9162]])
tensor([[0.2373]])
tensor([[0.0668]])
tensor([[-0.0109]])
tensor([[0.0668]])
tensor([[0.2288]])
tensor([[0.2676]])
tensor([[0.2676]])
tensor([[0.1415]])
tensor([[0.2235]])
tensor([[0.1819]])
tensor([[0.1469]])
tensor([[0.2901]])
tensor([[0.3212]])
tensor([[0.3812]])
tensor([[0.0282]])
tensor([[0.0282]])
tensor([[0.0282]])
tensor([[0.0282]])
tensor([[0.5291]])
tensor([[0.3384]])
tensor([[0.3742]])
tensor([[0.3742]])
tensor([[0.3814]])
tensor([[0.3814]])
tensor([[0.3746]])
tensor([[0.3746]])
tensor([[0.3835]])
tensor([[0.3835]])
tensor([[0.3936]])
tensor([[0.1543]])
tensor([[0.1543]])
tensor([[0.5656]])
tensor([[0.1543]])
tensor([[0.0235]])
tensor([[0.1543]])
tensor([[0.4410]])
tensor([[0.1543]])
tensor([[0.0521]])
tensor([[0.0760]])
tensor([[0.8933]])
tensor([[0.5080]])
tensor([[0.0287]])
tensor([[-0.0290]])
tensor([[0.6488]])
tensor([[0.1489]])
tensor([[0.6187]])
tensor([[0.3674]])
tensor([[0.3874]])
tensor([[1.]])
tensor([[0.3375]])
tensor([[0.6235]])
tensor([[0.1993]])
tensor([[0.0313]])
tensor([[0.5953]])
tensor([[0.6226]])
tensor([[0.4723]])
tensor([[0.5958]])
tensor([[0.4969]])
tensor([[0.0383]])
tensor([[0.1010]])
tensor([[0.3302]])
tensor([[0.0836]])
tensor([[0.8634]])
tensor([[0.8943]])
tensor([[0.5100]])
tensor([[0.0509]])
tensor([[-0.0069]])
tensor([[0.6644]])
tensor([[0.1710]])
tensor([[1.]])
tensor([[-0.0329]])
tensor([[0.1499]])
tensor([[1.]])
tensor([[0.1635]])
tensor([[0.1762]])
tensor([[0.1762]])
tensor([[0.3139]])
tensor([[0.4267]])
tensor([[0.2406]])
tensor([[0.2406]])
tensor([[0.5703]])
tensor([[0.7044]])
tensor([[0.1858]])
tensor([[0.3495]])
tensor([[0.3495]])
tensor([[0.1114]])
tensor([[0.6945]])
tensor([[0.7336]])
tensor([[0.6528]])
tensor([[0.2954]])
tensor([[0.2026]])
tensor([[0.2966]])
tensor([[0.3038]])
tensor([[0.1353]])
tensor([[0.1353]])
tensor([[0.3095]])
tensor([[0.7822]])
tensor([[1.0000]])
tensor([[0.0923]])
tensor([[0.1628]])
tensor([[0.5397]])
tensor([[0.0509]])
tensor([[-0.0060]])
tensor([[0.6173]])
tensor([[0.2285]])
tensor([[0.2591]])
tensor([[0.2679]])
tensor([[0.2976]])
tensor([[0.0078]])
tensor([[0.8532]])
tensor([[0.9233]])
tensor([[0.6796]])
tensor([[0.8532]])
tensor([[0.6796]])
tensor([[0.6399]])
tensor([[0.6796]])
tensor([[0.9327]])
tensor([[0.6190]])
tensor([[0.6692]])
tensor([[0.5519]])
tensor([[0.7653]])
tensor([[0.9920]])
tensor([[0.0742]])
tensor([[0.4120]])
tensor([[0.6202]])
tensor([[0.4274]])
tensor([[0.0558]])
tensor([[-0.0428]])
tensor([[0.5905]])
tensor([[0.2461]])
tensor([[0.3049]])
tensor([[1.]])
tensor([[0.3297]])
tensor([[0.2021]])
tensor([[0.3806]])
tensor([[0.3806]])
tensor([[0.5198]])
tensor([[0.4866]])
tensor([[0.0781]])
tensor([[0.9911]])
tensor([[0.9023]])
tensor([[0.9992]])
tensor([[0.5097]])
tensor([[1.0000]])
tensor([[0.7052]])
tensor([[0.4118]])
tensor([[0.5702]])
tensor([[0.1451]])
tensor([[0.4364]])
tensor([[0.3946]])
tensor([[0.3963]])
tensor([[0.0615]])
tensor([[0.5160]])
tensor([[-0.0839]])
tensor([[0.0762]])
tensor([[-0.0009]])
tensor([[0.6171]])
tensor([[0.3073]])
tensor([[1.0000]])
tensor([[0.1498]])
tensor([[0.2533]])
tensor([[0.1410]])
tensor([[0.1881]])
tensor([[0.1111]])
tensor([[0.2247]])
tensor([[0.1278]])
tensor([[0.1111]])
tensor([[0.0446]])
tensor([[0.2247]])
tensor([[0.0344]])
tensor([[0.2295]])
tensor([[0.4173]])
tensor([[0.6373]])
tensor([[1.0000]])
tensor([[0.1910]])
tensor([[0.4935]])
tensor([[0.6681]])
tensor([[0.6084]])
tensor([[0.6705]])
tensor([[0.4714]])
tensor([[0.0631]])
tensor([[0.5283]])
tensor([[0.4567]])
tensor([[0.5144]])
tensor([[0.1685]])
tensor([[0.4567]])

if using normal transformers as encoder/ not sentence transforemrs -->

In [ ]:
ds.to_csv(f"drive/MyDrive/monnetal/fold8/jina_reranker.csv", index=False)




```
"Tfidf"
"codeBERT"
"deepseek-ai/deepseek-coder-7b-instruct-v1.5"
"mistralai/Mistral-7B-v0.1"
"Sentence transformer"
"jinaai/jina-reranker-v3"
-->NDCG
```

In [ ]:
import torch

In [ ]:
# @title

print("Loading transformer model...")

model_name = "mistralai/Mistral-7B-v0.1"
# model_name = "deepseek-ai/deepseek-coder-1.3b-base"
#
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModel.from_pretrained(model_name, dtype=torch.float16)
model.to(device)
model.eval()
print("Model loaded")

Loading transformer model...

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/996 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

MistralModel LOAD REPORT from: mistralai/Mistral-7B-v0.1
Key            | Status     |  |
---------------+------------+--+-
lm_head.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Model loaded

In [ ]:
# @title

def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

def tf_encode(text,model=model,tokenizer=tokenizer,device=device):
    encoded = tokenizer(
        text,
        padding=True,
        truncation=False,
        return_tensors="pt"
    )

    encoded = {k: v.to(device) for k, v in encoded.items()}
    with torch.no_grad():
        model_output = model(**encoded)

    embed = mean_pooling(model_output, encoded['attention_mask'])
    return embed



def tf_encodex(
    text,
    model=model,
    tokenizer=tokenizer,
    device=device,
    max_tokens=512,
    overlap=50,
    fusion="mean"            # "mean" or "weighted"
):


    tokens = tokenizer(
        text,
        return_tensors="pt",
        truncation=False,
        padding=False
    )

    input_ids = tokens["input_ids"][0]
    attention_mask = tokens["attention_mask"][0]

    chunk_embeddings = []
    chunk_lengths = []

    stride = max_tokens - overlap
    total_len = input_ids.size(0)

    for start in range(0, total_len, stride):
        end = min(start + max_tokens, total_len)

        chunk_input_ids = input_ids[start:end].unsqueeze(0).to(device)
        chunk_attention_mask = attention_mask[start:end].unsqueeze(0).to(device)

        with torch.no_grad():
            model_output = model(
                input_ids=chunk_input_ids,
                attention_mask=chunk_attention_mask
            )

        chunk_embed = mean_pooling(model_output, chunk_attention_mask)

        chunk_embeddings.append(chunk_embed)
        chunk_lengths.append(chunk_attention_mask.sum().item())

    chunk_embeddings = torch.cat(chunk_embeddings, dim=0)

    if fusion == "weighted":
        weights = torch.tensor(chunk_lengths, device=device).unsqueeze(1)
        final_embedding = (chunk_embeddings * weights).sum(dim=0) / weights.sum()
    else:
        final_embedding = chunk_embeddings.mean(dim=0)

    return final_embedding.unsqueeze(0)

In [ ]:
# @title

c_model = torch.compile(model, mode="max-autotune")

In [ ]:
# @title

ds['score'] = None
torch.set_float32_matmul_precision('high')
pass_uid = None
pr_num = None
repo = None
pr = None
body = None
body_vec = None

for i in tqdm.tqdm(ds.index, desc="Re-ranking PR links"):
    # torch.cuda.empty_cache()

    # pr_name = ds.loc[i, "repo"]
    # pr_link = ds.loc[i, "pr_link"]


    try:
        if pass_uid != ds.loc[i, "uid"]:

            # pr_num = int(GITHUB_LINK_PATTERN.search(pr_link).group("pr"))
            # repo = g.get_repo(pr_name)
            # pr = repo.get_pull(pr_num)

            # body = pr.body or ""
            # ds.loc[i, "body"] = body
            body = ds.loc[i, "body"]
            body_vec = tf_encodex(
                body,
                model=model,
                tokenizer=tokenizer,
                device=device
            )

        doc_url = ds.loc[i, "link"]

        try:
            # doc = scrap(doc_url)
            # ds.loc[i, "doc"] = doc
            doc = ds.loc[i, "doc"]
            doc_vec = tf_encodex(
                doc,
                model=model,
                tokenizer=tokenizer,
                device=device
            )

            score = torch.cosine_similarity(
                body_vec,
                doc_vec,
                dim=1
            ).item()
            print(score)
            ds.loc[i, 'score'] = score

        except Exception:
            ds.loc[i, 'score'] = -1.0

    except Exception:
        ds.loc[i, 'score'] = -1.0
    pass_uid = ds.loc[i, "uid"]


ds['rerank'] = (
    ds
    .groupby("pr_link")['score']
    .rank(method="first", ascending=False)
    .astype("Int64")
)


out  = f"drive/MyDrive/monnetal/lastEval/Mistral7B.csv"

ds.to_csv(out, index=False)
print(f"Saved new evaluation to {out}")

Re-ranking PR links:   0%|          | 1/356 [00:00<01:44,  3.39it/s]

0.5084677338600159

Re-ranking PR links:   1%|          | 2/356 [00:01<03:17,  1.79it/s]

0.48664772510528564

Re-ranking PR links:   1%|          | 3/356 [00:01<03:44,  1.57it/s]

0.6136829853057861

Re-ranking PR links:   1%|          | 4/356 [00:02<03:54,  1.50it/s]

0.48664772510528564

Re-ranking PR links:   2%|▏         | 8/356 [00:02<01:17,  4.49it/s]

0.878475546836853
0.13089579343795776
0.053734056651592255
0.13089579343795776
0.13089579343795776

Re-ranking PR links:   4%|▎         | 13/356 [00:03<01:04,  5.28it/s]

-0.07793745398521423
-0.07793745398521423
-0.3637515902519226
-0.07793745398521423
-0.07793745398521423

Re-ranking PR links:   4%|▍         | 16/356 [00:03<00:44,  7.56it/s]

-0.18690645694732666
-0.07793745398521423

Re-ranking PR links:   5%|▌         | 18/356 [00:04<00:51,  6.58it/s]

0.48276302218437195
0.9767983555793762

Re-ranking PR links:   6%|▌         | 22/356 [00:04<00:36,  9.04it/s]

0.9272116422653198
0.7770758867263794
0.32143330574035645
0.057962726801633835

Re-ranking PR links:   7%|▋         | 24/356 [00:04<00:33,  9.89it/s]

1.0
0.8191894292831421

Re-ranking PR links:   7%|▋         | 26/356 [00:04<00:33,  9.95it/s]

0.822628378868103
0.8160128593444824
0.8453246355056763

Re-ranking PR links:   8%|▊         | 28/356 [00:05<00:30, 10.72it/s]

0.8128722310066223
0.8293415904045105

Re-ranking PR links:   8%|▊         | 30/356 [00:05<00:31, 10.31it/s]

0.7849901914596558
0.4448847770690918

Re-ranking PR links:  10%|▉         | 35/356 [00:06<00:36,  8.68it/s]

0.13031958043575287
-0.03870544582605362
-0.03870544582605362
-0.03870544582605362
-0.03870544582605362

Re-ranking PR links:  12%|█▏        | 41/356 [00:06<00:22, 13.73it/s]

-0.03870544582605362
-0.03870544582605362
-0.03870544582605362
-0.03870544582605362
-0.03870544582605362

Re-ranking PR links:  13%|█▎        | 45/356 [00:06<00:22, 14.04it/s]

0.870189368724823
0.5266094207763672
0.3182491660118103
0.11829641461372375

Re-ranking PR links:  13%|█▎        | 47/356 [00:06<00:28, 10.74it/s]

0.12367860972881317
0.40234464406967163
0.24152760207653046

Re-ranking PR links:  14%|█▍        | 49/356 [00:08<01:13,  4.18it/s]

0.2176472693681717
0.21326059103012085

Re-ranking PR links:  15%|█▍        | 52/356 [00:08<01:01,  4.97it/s]

0.16209463775157928
0.16209463775157928

Re-ranking PR links:  15%|█▌        | 55/356 [00:09<00:50,  5.93it/s]

0.07737496495246887
-0.158037930727005
0.7468954920768738

Re-ranking PR links:  16%|█▌        | 56/356 [00:09<01:13,  4.07it/s]

0.49604785442352295

Re-ranking PR links:  16%|█▋        | 58/356 [00:10<01:22,  3.63it/s]

0.49604785442352295
0.13224568963050842
0.36324143409729004

Re-ranking PR links:  17%|█▋        | 61/356 [00:10<00:46,  6.35it/s]

-0.04001564532518387
0.2643773853778839
0.2643773853778839

Re-ranking PR links:  19%|█▊        | 66/356 [00:10<00:33,  8.64it/s]

0.29092973470687866
0.9281759262084961
0.8907855749130249
1.0
0.8797410726547241

Re-ranking PR links:  19%|█▉        | 69/356 [00:11<00:25, 11.25it/s]

0.8764341473579407
0.09956967085599899

Re-ranking PR links:  20%|█▉        | 71/356 [00:11<00:32,  8.88it/s]

0.5988497138023376
0.8258653879165649
1.0
0.21452642977237701

Re-ranking PR links:  22%|██▏       | 77/356 [00:11<00:26, 10.48it/s]

0.6017774343490601
1.0
0.8284549713134766
0.9653530716896057

Re-ranking PR links:  23%|██▎       | 82/356 [00:12<00:24, 11.00it/s]

0.4249594211578369
0.9921075105667114
0.9939010739326477
0.9964362978935242
0.9999998807907104

Re-ranking PR links:  24%|██▎       | 84/356 [00:12<00:30,  8.87it/s]

0.6661508083343506
1.0
0.9494603872299194

Re-ranking PR links:  24%|██▍       | 86/356 [00:13<00:32,  8.18it/s]

0.40639728307724
0.9646929502487183
0.22328868508338928

Re-ranking PR links:  26%|██▌       | 91/356 [00:13<00:25, 10.28it/s]

0.19733251631259918
0.3264233469963074
0.30816492438316345

Re-ranking PR links:  26%|██▌       | 93/356 [00:13<00:27,  9.47it/s]

0.007112778723239899
0.4207914471626282

Re-ranking PR links:  27%|██▋       | 97/356 [00:14<00:24, 10.42it/s]

0.5145220756530762
0.9147680401802063
0.9255199432373047
0.6564053893089294

Re-ranking PR links:  28%|██▊       | 100/356 [00:14<00:19, 13.09it/s]

0.9048936367034912
0.6708030700683594
0.7608699798583984
0.8716428279876709

Re-ranking PR links:  29%|██▊       | 102/356 [00:14<00:18, 13.42it/s]

0.09720249474048615
0.8650943636894226

Re-ranking PR links:  29%|██▉       | 104/356 [00:14<00:21, 11.53it/s]

0.5298670530319214
0.5298670530319214

Re-ranking PR links:  30%|██▉       | 106/356 [00:15<00:32,  7.75it/s]

0.5484851598739624
0.9360793828964233

Re-ranking PR links:  31%|███       | 111/356 [00:15<00:28,  8.49it/s]

0.8389789462089539
0.933478593826294
0.9362568259239197
0.9279317259788513
0.9231635332107544

Re-ranking PR links:  32%|███▏      | 114/356 [00:15<00:22, 10.88it/s]

0.631828248500824
0.8136847019195557
0.8765615224838257
0.9329694509506226

Re-ranking PR links:  33%|███▎      | 119/356 [00:16<00:22, 10.66it/s]

0.6370359659194946
0.465545654296875
0.14483784139156342

Re-ranking PR links:  34%|███▍      | 121/356 [00:16<00:27,  8.52it/s]

0.6003432273864746
0.14483784139156342
0.500714123249054

Re-ranking PR links:  35%|███▍      | 123/356 [00:16<00:26,  8.91it/s]

0.14483784139156342
0.43123936653137207

Re-ranking PR links:  35%|███▌      | 126/356 [00:17<00:36,  6.27it/s]

0.3040359318256378
0.3040359318256378

Re-ranking PR links:  37%|███▋      | 130/356 [00:17<00:25,  8.94it/s]

0.36354145407676697
0.06484393030405045
0.10323067009449005
0.06484393030405045
0.10323067009449005
0.06484393030405045

Re-ranking PR links:  38%|███▊      | 135/356 [00:18<00:27,  8.04it/s]

0.20928925275802612
0.10323067009449005
0.8207560777664185

Re-ranking PR links:  38%|███▊      | 137/356 [00:18<00:25,  8.46it/s]

0.8207560777664185
0.84592205286026
0.7987365126609802

Re-ranking PR links:  40%|███▉      | 142/356 [00:19<00:27,  7.69it/s]

0.4330083727836609
0.4850786030292511
0.9153627157211304
0.2667922377586365
0.17735612392425537

Re-ranking PR links:  40%|████      | 144/356 [00:19<00:24,  8.73it/s]

0.026147061958909035
0.23610587418079376

Re-ranking PR links:  42%|████▏     | 148/356 [00:20<00:23,  8.77it/s]

0.585562527179718
0.7882511019706726
0.9328420162200928
0.9397581815719604

Re-ranking PR links:  43%|████▎     | 154/356 [00:20<00:14, 13.83it/s]

0.123310886323452
0.6407891511917114
0.8776657581329346
0.7113863229751587
0.7012739181518555

Re-ranking PR links:  44%|████▍     | 156/356 [00:20<00:16, 11.90it/s]

0.9182908535003662
0.7344381809234619

Re-ranking PR links:  44%|████▍     | 158/356 [00:21<00:20,  9.80it/s]

0.7385321855545044
0.7745288610458374
0.7683303356170654

Re-ranking PR links:  46%|████▌     | 163/356 [00:21<00:19, 10.09it/s]

0.26938390731811523
1.0
0.08674989640712738
0.31830981373786926

Re-ranking PR links:  47%|████▋     | 166/356 [00:21<00:17, 10.93it/s]

0.004477709531784058
0.004477709531784058
0.29469043016433716

Re-ranking PR links:  47%|████▋     | 169/356 [00:22<00:16, 11.45it/s]

0.29469043016433716
0.3699713945388794
0.7181751728057861

Re-ranking PR links:  48%|████▊     | 171/356 [00:22<00:15, 12.01it/s]

0.408333420753479
0.03239677473902702
0.29524096846580505

Re-ranking PR links:  49%|████▊     | 173/356 [00:22<00:14, 12.32it/s]

0.03239677473902702
0.38497114181518555

Re-ranking PR links:  49%|████▉     | 175/356 [00:22<00:23,  7.71it/s]

0.5137991309165955

Re-ranking PR links:  50%|████▉     | 177/356 [00:23<00:25,  6.94it/s]

0.5137991309165955
0.44008100032806396
0.3035660982131958

Re-ranking PR links:  50%|█████     | 179/356 [00:23<00:24,  7.22it/s]

0.33798855543136597

Re-ranking PR links:  51%|█████     | 180/356 [00:26<01:56,  1.51it/s]

0.49753135442733765

Re-ranking PR links:  51%|█████     | 181/356 [00:27<01:44,  1.68it/s]

0.661618173122406

Re-ranking PR links:  52%|█████▏    | 185/356 [00:27<00:48,  3.50it/s]

0.6682873964309692
0.22195842862129211
-0.1201525330543518
-0.1201525330543518
-0.1201525330543518
-0.1201525330543518

Re-ranking PR links:  53%|█████▎    | 190/356 [00:28<00:45,  3.64it/s]

0.29928597807884216
0.10907945036888123
0.09751070290803909

Re-ranking PR links:  54%|█████▍    | 192/356 [00:29<00:38,  4.21it/s]

0.09751070290803909
0.10730163007974625

Re-ranking PR links:  54%|█████▍    | 194/356 [00:29<00:33,  4.84it/s]

0.10730163007974625
0.09839879721403122

Re-ranking PR links:  55%|█████▌    | 196/356 [00:29<00:29,  5.42it/s]

0.09839879721403122
0.08188284933567047

Re-ranking PR links:  55%|█████▌    | 197/356 [00:30<00:28,  5.66it/s]

0.08188284933567047

Re-ranking PR links:  56%|█████▋    | 201/356 [00:30<00:26,  5.93it/s]

0.3090061545372009
0.042395830154418945
0.042395830154418945
0.5153325200080872
0.042395830154418945

Re-ranking PR links:  57%|█████▋    | 204/356 [00:31<00:17,  8.83it/s]

0.162887841463089
0.042395830154418945
0.4697669744491577
0.042395830154418945

Re-ranking PR links:  58%|█████▊    | 207/356 [00:31<00:13, 10.65it/s]

0.432689905166626

Re-ranking PR links:  59%|█████▊    | 209/356 [00:31<00:15,  9.63it/s]

0.46974238753318787
0.901016116142273
0.27845966815948486
0.2010381519794464

Re-ranking PR links:  60%|█████▉    | 212/356 [00:31<00:12, 11.32it/s]

0.03786702826619148
0.2830427289009094

Re-ranking PR links:  61%|██████    | 216/356 [00:32<00:15,  8.99it/s]

0.18098881840705872
0.6132311820983887
0.9068227410316467

Re-ranking PR links:  61%|██████    | 218/356 [00:32<00:13,  9.99it/s]

0.35482972860336304
1.0
0.554714560508728

Re-ranking PR links:  62%|██████▏   | 220/356 [00:32<00:13,  9.99it/s]

0.9072622060775757

Re-ranking PR links:  63%|██████▎   | 224/356 [00:33<00:14,  9.31it/s]

0.34545761346817017
0.3003122806549072
0.9211053848266602
0.7807735204696655

Re-ranking PR links:  64%|██████▍   | 227/356 [00:33<00:10, 11.95it/s]

0.47491830587387085
0.9227962493896484
0.318764328956604
0.19088563323020935

Re-ranking PR links:  64%|██████▍   | 229/356 [00:33<00:10, 12.41it/s]

0.005829149857163429
0.19870483875274658

Re-ranking PR links:  66%|██████▌   | 234/356 [00:33<00:10, 11.72it/s]

0.4635622501373291
0.9650713205337524
0.9558780193328857
0.2907584011554718
0.22895672917366028

Re-ranking PR links:  66%|██████▋   | 236/356 [00:34<00:09, 12.22it/s]

0.0522269681096077
0.3197343349456787

Re-ranking PR links:  67%|██████▋   | 238/356 [00:34<00:14,  8.08it/s]

0.21709361672401428
1.0
0.04616304486989975

Re-ranking PR links:  68%|██████▊   | 241/356 [00:34<00:14,  7.87it/s]

0.5173803567886353
1.0

Re-ranking PR links:  69%|██████▉   | 245/356 [00:35<00:13,  8.03it/s]

0.5300916433334351
-0.01495615765452385
0.543472945690155

Re-ranking PR links:  70%|██████▉   | 248/356 [00:35<00:11,  9.33it/s]

0.543472945690155
0.4743525981903076
0.7235499024391174
0.5114794969558716

Re-ranking PR links:  71%|███████   | 252/356 [00:36<00:20,  5.03it/s]

0.5114794969558716
0.6522423624992371
0.8158807754516602

Re-ranking PR links:  71%|███████▏  | 254/356 [00:37<00:17,  5.72it/s]

0.3059271574020386
0.7925937175750732

Re-ranking PR links:  72%|███████▏  | 255/356 [00:37<00:17,  5.83it/s]

0.7925937175750732

Re-ranking PR links:  72%|███████▏  | 258/356 [00:37<00:15,  6.25it/s]

0.5566691160202026
0.8242440223693848
0.8860033750534058

Re-ranking PR links:  73%|███████▎  | 259/356 [00:38<00:17,  5.50it/s]

0.80064857006073

Re-ranking PR links:  73%|███████▎  | 260/356 [00:38<00:20,  4.72it/s]

0.43347227573394775

Re-ranking PR links:  73%|███████▎  | 261/356 [00:39<00:36,  2.57it/s]

0.5588440895080566

Re-ranking PR links:  74%|███████▎  | 262/356 [00:40<00:44,  2.13it/s]

0.4806918203830719

Re-ranking PR links:  74%|███████▍  | 263/356 [00:40<00:47,  1.98it/s]

0.44726812839508057

Re-ranking PR links:  74%|███████▍  | 264/356 [00:41<00:47,  1.93it/s]

0.3992312252521515

Re-ranking PR links:  74%|███████▍  | 265/356 [00:41<00:47,  1.90it/s]

0.3992312252521515

Re-ranking PR links:  75%|███████▍  | 266/356 [00:42<00:41,  2.16it/s]

0.41690579056739807
0.9864223003387451
1.0

Re-ranking PR links:  76%|███████▋  | 272/356 [00:42<00:13,  6.11it/s]

0.3872087597846985
0.2651230990886688
0.2997370660305023
0.23842382431030273

Re-ranking PR links:  77%|███████▋  | 274/356 [00:42<00:12,  6.55it/s]

0.032930273562669754
0.3075234293937683

Re-ranking PR links:  78%|███████▊  | 277/356 [00:43<00:09,  8.53it/s]

0.541109025478363
0.4361545443534851
0.5943233966827393

Re-ranking PR links:  78%|███████▊  | 279/356 [00:44<00:20,  3.82it/s]

0.22162893414497375
-0.08680576831102371

Re-ranking PR links:  79%|███████▉  | 282/356 [00:44<00:14,  5.02it/s]

0.809671938419342
0.9349921941757202
0.9193713068962097

Re-ranking PR links:  79%|███████▉  | 283/356 [00:44<00:13,  5.50it/s]

0.809671938419342
0.9193713068962097

Re-ranking PR links:  80%|████████  | 285/356 [00:44<00:11,  6.19it/s]

0.8172703981399536
0.9193713068962097

Re-ranking PR links:  81%|████████  | 288/356 [00:45<00:09,  6.94it/s]

0.9946964979171753
0.7150866985321045
0.8224831223487854

Re-ranking PR links:  82%|████████▏ | 291/356 [00:45<00:07,  8.16it/s]

0.631849467754364
0.42558228969573975
0.9774062633514404

Re-ranking PR links:  83%|████████▎ | 294/356 [00:46<00:10,  5.66it/s]

0.7960308790206909
0.7735934257507324

Re-ranking PR links:  84%|████████▎ | 298/356 [00:46<00:07,  7.36it/s]

0.9367338418960571
0.19588181376457214
0.2331472933292389
0.05991643667221069

Re-ranking PR links:  84%|████████▍ | 299/356 [00:46<00:07,  7.17it/s]

0.28492769598960876

Re-ranking PR links:  84%|████████▍ | 300/356 [00:47<00:09,  5.63it/s]

0.1282191276550293
0.610396683216095
0.9999998807907104

Re-ranking PR links:  86%|████████▌ | 305/356 [00:48<00:07,  6.67it/s]

0.6187217235565186
0.5703065395355225
0.5316637754440308
0.5316637754440308

Re-ranking PR links:  86%|████████▌ | 307/356 [00:48<00:06,  7.97it/s]

0.7016403675079346

Re-ranking PR links:  87%|████████▋ | 309/356 [00:48<00:06,  7.49it/s]

0.6633776426315308
0.19639720022678375
0.97421795129776
0.7433202266693115

Re-ranking PR links:  88%|████████▊ | 315/356 [00:48<00:03, 11.77it/s]

0.9984033107757568
0.8967358469963074
0.9999999403953552
0.6428245902061462

Re-ranking PR links:  89%|████████▉ | 317/356 [00:48<00:03, 12.15it/s]

0.7105351686477661
0.5901056528091431
0.23939242959022522

Re-ranking PR links:  90%|████████▉ | 319/356 [00:50<00:09,  3.90it/s]

0.38570284843444824
0.347606360912323

Re-ranking PR links:  90%|█████████ | 321/356 [00:52<00:14,  2.42it/s]

0.3892050087451935

Re-ranking PR links:  91%|█████████ | 323/356 [00:52<00:11,  2.98it/s]

0.38055217266082764
0.8294414281845093
0.058827828615903854

Re-ranking PR links:  92%|█████████▏| 326/356 [00:52<00:06,  4.71it/s]

0.22597184777259827
0.03488661348819733

Re-ranking PR links:  92%|█████████▏| 327/356 [00:52<00:05,  4.94it/s]

0.2748672664165497

Re-ranking PR links:  93%|█████████▎| 331/356 [00:53<00:03,  6.74it/s]

0.028062567114830017
1.0
0.9397710561752319
0.5726227760314941

Re-ranking PR links:  94%|█████████▍| 334/356 [00:53<00:02,  9.33it/s]

0.5190820097923279
0.6847789287567139
0.4545325040817261
0.6933038234710693

Re-ranking PR links:  95%|█████████▍| 338/356 [00:53<00:01, 10.29it/s]

0.5093268156051636
0.4545325040817261
0.4339669346809387

Re-ranking PR links:  96%|█████████▌| 340/356 [00:53<00:01, 11.08it/s]

0.6933038234710693
0.4956878423690796

Re-ranking PR links:  96%|█████████▌| 342/356 [00:54<00:01,  7.96it/s]

0.42201822996139526
0.684056282043457
0.8685474395751953
0.9999999403953552

Re-ranking PR links:  97%|█████████▋| 347/356 [00:54<00:00,  9.36it/s]

0.4397123456001282
0.8982275128364563
0.9113771915435791
0.9451495409011841
0.9102325439453125

Re-ranking PR links:  98%|█████████▊| 350/356 [00:54<00:00, 12.00it/s]

0.3162246346473694
0.0342179536819458

Re-ranking PR links:  99%|█████████▉| 352/356 [00:55<00:00, 10.59it/s]

0.2665315866470337
0.811923623085022

Re-ranking PR links:  99%|█████████▉| 354/356 [00:55<00:00, 10.36it/s]

0.6351557970046997

Re-ranking PR links: 100%|██████████| 356/356 [00:56<00:00,  6.30it/s]

0.6307756900787354
0.811923623085022
Saved new evaluation to drive/MyDrive/monnetal/lastEval/Mistral7B.csv

In [ ]:
ds

,uid,pr_link,repo,pr_title,link_index,link,label_word,link_count,media_type,isGithub,rank,score,rerank,body,doc
0,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,0,https://github.com/tensorflow/tensorflow/blob/...,git_configure.bzl,4.0,NaN,NaN,1,0.508507,2,[git_configure.bzl](https://github.com/tensorf...,tensorflow/third_party/git/git_configure.bzl a...
1,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,1,https://github.com/tensorflow/tensorflow/blob/...,tools/git/gen_git_source.py,4.0,NaN,NaN,2,0.486539,3,[git_configure.bzl](https://github.com/tensorf...,tensorflow/tensorflow/tools/git/gen_git_source...
2,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,2,https://github.com/tensorflow/tensorflow/commi...,https://github.com/tensorflow/tensorflow/commi...,4.0,NaN,NaN,3,0.613135,1,[git_configure.bzl](https://github.com/tensorf...,PY3 Migration - //tensorflow/tools [2] · tenso...
3,6,https://github.com/tensorflow/tensorflow/pull/...,tensorflow/tensorflow,Removed six dependency in tools/git since it b...,3,https://github.com/tensorflow/tensorflow/blob/...,https://github.com/tensorflow/tensorflow/blob/...,4.0,NaN,NaN,4,0.486539,4,[git_configure.bzl](https://github.com/tensorf...,tensorflow/tensorflow/tools/git/gen_git_source...
4,14,https://github.com/pytorch/pytorch/pull/123106,pytorch/pytorch,nn.Module: use swap_tensors for Tensor subclas...,0,https://github.com/pytorch/pytorch/pull/122755,#122755,3.0,NaN,NaN,1,0.977866,1,This fixes a bug when casting a module that ha...,This fixes a bug when casting a module that ha...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,685,https://github.com/huggingface/transformers/pu...,huggingface/transformers,Switch from using sum for flattening lists of ...,3,https://github.com/huggingface/transformers/tr...,here are tips on formatting docstrings,4.0,NaN,NaN,4,0.578668,2,# Speed up list flattening in `group_texts` b...,transformers/docs at main · huggingface/transf...
338,695,https://github.com/yt-dlp/yt-dlp/pull/2223,yt-dlp/yt-dlp,[youtube] Fix inconsistent date timezones (ens...,0,http://unlicense.org/,Unlicense,4.0,NaN,NaN,4,0.30039,4,## Please follow the guide below\r\n\r\n- You ...,404 no body found
339,695,https://github.com/yt-dlp/yt-dlp/pull/2223,yt-dlp/yt-dlp,[youtube] Fix inconsistent date timezones (ens...,1,https://github.com/yt-dlp/yt-dlp/issues/1881,#1881,4.0,NaN,NaN,2,0.746361,3,## Please follow the guide below\r\n\r\n- You ...,### Checklist\n\n- [X] I'm asking a question a...
340,695,https://github.com/yt-dlp/yt-dlp/pull/2223,yt-dlp/yt-dlp,[youtube] Fix inconsistent date timezones (ens...,2,https://github.com/yt-dlp/yt-dlp/issues/2069,#2069,4.0,NaN,NaN,3,0.91462,1,## Please follow the guide below\r\n\r\n- You ...,## Please follow the guide below\r\n\r\n- You ...
341,695,https://github.com/yt-dlp/yt-dlp/pull/2223,yt-dlp/yt-dlp,[youtube] Fix inconsistent date timezones (ens...,3,https://github.com/yt-dlp/yt-dlp/issues/1067,#1067,4.0,NaN,NaN,1,0.906166,2,## Please follow the guide below\r\n\r\n- You ...,<!--\r\n\r\n##################################...

In [ ]:
output_path = "drive/MyDrive/monnetal/ds_save.csv"
ds = ds.drop(columns=['rerank'], errors='ignore') # Drop 'rerank' column if it exists
ds = ds.drop(columns=['score'], errors='ignore')
ds.to_csv(output_path, index=False)
print(f"DataFrame 'ds' saved to {output_path}")

DataFrame 'ds' saved to drive/MyDrive/monnetal/ds_save.csv

TFIDF trickery

In [ ]:

def software_tokenizer(text):
    # Split CamelCase and snake_case
    tokens = re.sub(r'([a-z])([A-Z])', r'\1 \2', text) # camelCase
    tokens = tokens.replace('_', ' ')                  # snake_case
    return tokens.lower().split()

In [ ]:
# @title
repo_list = ds["repo"].unique()

In [ ]:
repo_list

array(['tensorflow/tensorflow', 'pytorch/pytorch', 'n8n-io/n8n',
       'flutter/flutter', 'microsoft/powertoys', 'vercel/next.js',
       'godotengine/godot', 'ant-design/ant-design',
       'huggingface/transformers', 'bitcoin/bitcoin',
       'kubernetes/kubernetes', 'storybookjs/storybook',
       'excalidraw/excalidraw', 'mui/material-ui', 'angular/angular',
       'rust-lang/rust', 'microsoft/typescript',
       'Significant-Gravitas/AutoGPT'], dtype=object)

In [ ]:
# @title
import json
import os
from tqdm.notebook import tqdm


# proto


def load_existing_bodies(BODIES_FILE):
    if os.path.exists(BODIES_FILE):
        bodies = []
        with open(BODIES_FILE, 'r', encoding='utf-8') as f:
            for line in f:
                bodies.append(json.loads(line.strip()))
        return bodies
    return []

def save_body_to_file(body,BODIES_FILE):
    with open(BODIES_FILE, 'a', encoding='utf-8') as f:
        f.write(json.dumps(body, ensure_ascii=False) + '\n')


BODIES_FILE = f"drive/MyDrive/monnetal/idf/{repo_list[i]}"
pr_bodies = load_existing_bodies(BODIES_FILE)

for i in tqdm(range(len(repo_list)), desc="retrieve PRs"):
    repo_name = repo_list[i]
    repo = g.get_repo(repo_name)
    prs = repo.get_pulls(state="all")
    for pr in prs:

        BODIES_FILE = f"drive/MyDrive/monnetal/idf/{repo_list[i]}"
        body = pr.body or ""
        pr_bodies.append(body)
        save_body_to_file(body,BODIES_FILE)

In [ ]:
import json
import os
import time
import logging
from tqdm.notebook import tqdm

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_existing_bodies(bodies_file):
    """Load existing PR bodies from file with error handling"""
    if os.path.exists(bodies_file):
        bodies = []
        try:
            with open(bodies_file, 'r', encoding='utf-8') as f:
                for line_num, line in enumerate(f, 1):
                    try:
                        if line.strip():  # Skip empty lines
                            bodies.append(json.loads(line.strip()))
                    except json.JSONDecodeError as e:
                        logger.warning(f"Skipping invalid JSON at line {line_num} in {bodies_file}: {e}")
                        continue
            logger.info(f"Loaded {len(bodies)} existing PR bodies from {bodies_file}")
            return bodies
        except Exception as e:
            logger.error(f"Error loading bodies from {bodies_file}: {e}")
            return []
    return []

def save_body_to_file(body, bodies_file, max_retries=3):
    """Save single body to file with retry mechanism"""
    for attempt in range(max_retries):
        try:
            # Ensure directory exists
            os.makedirs(os.path.dirname(bodies_file), exist_ok=True)

            with open(bodies_file, 'a', encoding='utf-8') as f:
                f.write(json.dumps(body, ensure_ascii=False) + '\n')
            return True
        except Exception as e:
            logger.warning(f"Attempt {attempt + 1} failed to save to {bodies_file}: {e}")
            if attempt < max_retries - 1:
                time.sleep(1)  # Wait before retry
            else:
                logger.error(f"Failed to save after {max_retries} attempts: {e}")
                return False

def save_checkpoint(checkpoint_file, current_repo_index, processed_prs):
    """Save checkpoint with current progress"""
    try:
        checkpoint_data = {
            'current_repo_index': current_repo_index,
            'processed_prs': processed_prs,
            'timestamp': time.time()
        }
        os.makedirs(os.path.dirname(checkpoint_file), exist_ok=True)
        with open(checkpoint_file, 'w', encoding='utf-8') as f:
            json.dump(checkpoint_data, f)
        logger.info(f"Checkpoint saved at repo index {current_repo_index}")
    except Exception as e:
        logger.error(f"Failed to save checkpoint: {e}")

def load_checkpoint(checkpoint_file):
    """Load checkpoint to resume processing"""
    try:
        if os.path.exists(checkpoint_file):
            with open(checkpoint_file, 'r', encoding='utf-8') as f:
                checkpoint_data = json.load(f)
            logger.info(f"Resuming from repo index {checkpoint_data['current_repo_index']}")
            return checkpoint_data['current_repo_index'], checkpoint_data.get('processed_prs', 0)
    except Exception as e:
        logger.error(f"Failed to load checkpoint: {e}")
    return 0, 0

def get_safe_filename(repo_name):
    """Convert repo name to safe filename"""
    return repo_name.replace('/', '_').replace('\\', '_')

# Configuration
BASE_DIR = "drive/MyDrive/monnetal/idf"
CHECKPOINT_FILE = f"{BASE_DIR}/processing_checkpoint.json"
ERROR_LOG_FILE = f"{BASE_DIR}/error_log.txt"

# Ensure base directory exists
os.makedirs(BASE_DIR, exist_ok=True)

# Load checkpoint to resume processing
start_repo_index, total_processed_prs = load_checkpoint(CHECKPOINT_FILE)
logger.info(f"Starting from repo index {start_repo_index}, total PRs processed so far: {total_processed_prs}")

# Initialize progress tracking
repo_errors = []
total_prs_current_session = 0

try:
    for i in tqdm(range(start_repo_index, len(repo_list)), desc="retrieve PRs", initial=start_repo_index, total=len(repo_list)):
        repo_name = repo_list[i]
        safe_repo_name = get_safe_filename(repo_name)
        bodies_file = f"{BASE_DIR}/{safe_repo_name}.jsonl"

        try:
            # Load existing bodies for this repo
            pr_bodies = load_existing_bodies(bodies_file)
            existing_count = len(pr_bodies)

            # Get repository
            repo = g.get_repo(repo_name)
            prs = repo.get_pulls(state="all")

            repo_pr_count = 0
            for pr_index, pr in enumerate(tqdm(prs, desc=f"Processing PRs from {repo_name}", leave=False)):
                try:
                    # Skip if we already have this PR (simple check by count)
                    if pr_index < existing_count:
                        continue

                    body = pr.body or ""

                    # Save to file immediately
                    if save_body_to_file(body, bodies_file):
                        pr_bodies.append(body)
                        repo_pr_count += 1
                        total_prs_current_session += 1
                    else:
                        # Log failed save
                        error_msg = f"Failed to save PR #{pr.number} from {repo_name}\n"
                        with open(ERROR_LOG_FILE, 'a', encoding='utf-8') as f:
                            f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} - {error_msg}")

                except Exception as pr_error:
                    logger.error(f"Error processing PR in {repo_name}: {pr_error}")
                    continue

            logger.info(f"Processed {repo_pr_count} new PRs from {repo_name} (total: {len(pr_bodies)})")

        except Exception as repo_error:
            error_msg = f"Error processing repository {repo_name}: {repo_error}"
            logger.error(error_msg)
            repo_errors.append((repo_name, str(repo_error)))

            # Save error to file
            with open(ERROR_LOG_FILE, 'a', encoding='utf-8') as f:
                f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} - {error_msg}\n")
            continue

        # Save checkpoint every 5 repositories
        if (i + 1) % 5 == 0:
            save_checkpoint(CHECKPOINT_FILE, i + 1, total_processed_prs + total_prs_current_session)

        # Optional: Add small delay to avoid rate limiting
        time.sleep(0.1)

except KeyboardInterrupt:
    logger.info("Processing interrupted by user")
    save_checkpoint(CHECKPOINT_FILE, i, total_processed_prs + total_prs_current_session)
except Exception as e:
    logger.error(f"Unexpected error during processing: {e}")
    save_checkpoint(CHECKPOINT_FILE, i if 'i' in locals() else start_repo_index, total_processed_prs + total_prs_current_session)
finally:
    # Final checkpoint save
    final_index = i if 'i' in locals() else start_repo_index
    save_checkpoint(CHECKPOINT_FILE, final_index, total_processed_prs + total_prs_current_session)

    # Summary report
    logger.info(f"Processing completed/stopped at repo index {final_index}")
    logger.info(f"Total PRs processed this session: {total_prs_current_session}")
    logger.info(f"Repositories with errors: {len(repo_errors)}")

    if repo_errors:
        logger.info("Repositories that had errors:")
        for repo_name, error in repo_errors[:10]:  # Show first 10 errors
            logger.info(f"  - {repo_name}: {error}")

    print(f"\n=== SUMMARY for {repo_list[i]} ===")
    print(f"Processed repos: {final_index - start_repo_index}")
    print(f"New PRs collected: {total_prs_current_session}")
    print(f"Repos with errors: {len(repo_errors)}")
    print(f"Checkpoint saved. You can resume by running the same code.")

retrieve PRs:   0%|          | 0/18 [00:00<?, ?it/s]

Processing PRs from tensorflow/tensorflow: 0it [00:00, ?it/s]

Processing PRs from pytorch/pytorch: 0it [00:00, ?it/s]

Processing PRs from n8n-io/n8n: 0it [00:00, ?it/s]

Processing PRs from flutter/flutter: 0it [00:00, ?it/s]

Processing PRs from microsoft/powertoys: 0it [00:00, ?it/s]

Processing PRs from vercel/next.js: 0it [00:00, ?it/s]

Processing PRs from godotengine/godot: 0it [00:00, ?it/s]

Processing PRs from ant-design/ant-design: 0it [00:00, ?it/s]

Processing PRs from huggingface/transformers: 0it [00:00, ?it/s]

Processing PRs from bitcoin/bitcoin: 0it [00:00, ?it/s]

Processing PRs from kubernetes/kubernetes: 0it [00:00, ?it/s]

Processing PRs from storybookjs/storybook: 0it [00:00, ?it/s]

Processing PRs from excalidraw/excalidraw: 0it [00:00, ?it/s]

Processing PRs from mui/material-ui: 0it [00:00, ?it/s]

Processing PRs from angular/angular: 0it [00:00, ?it/s]

Processing PRs from rust-lang/rust: 0it [00:00, ?it/s]

Processing PRs from microsoft/typescript: 0it [00:00, ?it/s]

Processing PRs from Significant-Gravitas/AutoGPT: 0it [00:00, ?it/s]

=== SUMMARY for Significant-Gravitas/AutoGPT ===
Processed repos: 17
New PRs collected: 752870
Repos with errors: 0
Checkpoint saved. You can resume by running the same code.

In [ ]:
def get_bodies_from_repo(repo_name):
    """Load PR bodies from a specific repository"""
    safe_repo_name = get_safe_filename(repo_name)
    bodies_file = f"{BASE_DIR}/{safe_repo_name}.jsonl"

    bodies = load_existing_bodies(bodies_file)
    print(f"Loaded {len(bodies)} PR bodies from {repo_name}")
    return bodies

# # Usage
# repo_bodies = get_bodies_from_repo("facebook/react")
# print(f"React repo has {len(repo_bodies)} PR bodies")

In [ ]:
import json
import os
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm

def create_tf_idf_vectorizers():
    """Create TF-IDF vectorizers for each repository from saved corpus"""

    BASE_DIR = "drive/MyDrive/monnetal/idf"
    tf_idf_dict = {}

    print("Creating TF-IDF vectorizers from saved corpus...")

    for repo_name in tqdm(repo_list, desc="Creating vectorizers"):
        safe_repo_name = get_safe_filename(repo_name)
        bodies_file = f"{BASE_DIR}/{safe_repo_name}.jsonl"

        try:
            # Load PR bodies for this repository
            pr_bodies = load_existing_bodies(bodies_file)

            if len(pr_bodies) == 0:
                print(f"No bodies found for {repo_name}, skipping...")
                continue

            # Filter out empty bodies
            non_empty_bodies = [body for body in pr_bodies if body and body.strip()]

            if len(non_empty_bodies) < 2:
                print(f"Not enough non-empty bodies for {repo_name}, skipping...")
                continue

            # Create TF-IDF vectorizer for this repository
            vectorizer = TfidfVectorizer(
                max_features=5000,
                min_df=2,  # Ignore terms that appear in less than 2 documents
                max_df=0.8,  # Ignore terms that appear in more than 80% of documents
                stop_words='english',
                ngram_range=(1, 2),  # Use unigrams and bigrams
                lowercase=True,
                strip_accents='unicode'
            )

            # Fit the vectorizer on PR bodies
            vectorizer.fit(non_empty_bodies)

            tf_idf_dict[repo_name] = {
                'vectorizer': vectorizer,
                'corpus_size': len(non_empty_bodies),
                'total_features': len(vectorizer.get_feature_names_out())
            }

            print(f"Created vectorizer for {repo_name}: {len(non_empty_bodies)} PRs, {len(vectorizer.get_feature_names_out())} features")

        except Exception as e:
            print(f"Error creating vectorizer for {repo_name}: {e}")
            continue

    return tf_idf_dict

# Create the vectorizers
tf_idf = create_tf_idf_vectorizers()
print(f"Successfully created vectorizers for {len(tf_idf)} repositories")
def save_tf_idf_vectorizers(tf_idf_dict, save_path="drive/MyDrive/monnetal/tf_idf_vectorizers.pkl"):
    """Save the TF-IDF vectorizers to disk"""
    try:
        with open(save_path, 'wb') as f:
            pickle.dump(tf_idf_dict, f)
        print(f"TF-IDF vectorizers saved to {save_path}")
    except Exception as e:
        print(f"Error saving vectorizers: {e}")

def load_tf_idf_vectorizers(save_path="drive/MyDrive/monnetal/tf_idf_vectorizers.pkl"):
    """Load the TF-IDF vectorizers from disk"""
    try:
        with open(save_path, 'rb') as f:
            tf_idf_dict = pickle.load(f)
        print(f"Loaded TF-IDF vectorizers for {len(tf_idf_dict)} repositories")
        return tf_idf_dict
    except Exception as e:
        print(f"Error loading vectorizers: {e}")
        return {}

# Save the vectorizers
save_tf_idf_vectorizers(tf_idf)

Creating TF-IDF vectorizers from saved corpus...

Creating vectorizers:   0%|          | 0/18 [00:00<?, ?it/s]

Created vectorizer for tensorflow/tensorflow: 68170 PRs, 5000 features
Created vectorizer for pytorch/pytorch: 119020 PRs, 5000 features
Created vectorizer for n8n-io/n8n: 18250 PRs, 5000 features
Created vectorizer for flutter/flutter: 67850 PRs, 5000 features
Created vectorizer for microsoft/powertoys: 7745 PRs, 5000 features
Created vectorizer for vercel/next.js: 35360 PRs, 5000 features
Created vectorizer for godotengine/godot: 54079 PRs, 5000 features
Created vectorizer for ant-design/ant-design: 21537 PRs, 5000 features
Created vectorizer for huggingface/transformers: 25247 PRs, 5000 features
Created vectorizer for bitcoin/bitcoin: 22847 PRs, 5000 features
Created vectorizer for kubernetes/kubernetes: 86236 PRs, 5000 features
Created vectorizer for storybookjs/storybook: 15612 PRs, 5000 features
Created vectorizer for excalidraw/excalidraw: 5017 PRs, 5000 features
Created vectorizer for mui/material-ui: 25806 PRs, 5000 features
Created vectorizer for angular/angular: 31957 PRs, 5000 features
Created vectorizer for rust-lang/rust: 87240 PRs, 5000 features
Created vectorizer for microsoft/typescript: 18167 PRs, 5000 features
Created vectorizer for Significant-Gravitas/AutoGPT: 7808 PRs, 5000 features
Successfully created vectorizers for 18 repositories
TF-IDF vectorizers saved to drive/MyDrive/monnetal/tf_idf_vectorizers.pkl

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import re

# Load vectorizers if not already loaded
if 'tf_idf' not in globals() or not tf_idf:
    tf_idf = load_tf_idf_vectorizers()

# Your existing pattern
GITHUB_LINK_PATTERN = re.compile(r'github\.com/[\w.-]+/[\w.-]+/pull/(?P<pr>\d+)')

# Initialize variables
pass_uid = None
pr_num = None
repo = None
pr = None
body = None
body_vec = None
vec = None

print(f"Starting re-ranking with vectorizers for {len(tf_idf)} repositories...")

for i in tqdm(ds.index, desc="Re-ranking PR links"):
    repo_name = ds.loc[i, "repo"]
    pr_link = ds.loc[i, "pr_link"]

    try:
        if pass_uid != ds.loc[i, "uid"]:
            pr_num = int(GITHUB_LINK_PATTERN.search(pr_link).group("pr"))

            # Check if we have a vectorizer for this repository
            if repo_name not in tf_idf:
                print(f"No vectorizer found for {repo_name}, using default score")
                ds.loc[i, 'score'] = -1.0
                pass_uid = ds.loc[i, "uid"]
                continue

            # Get vectorizer for this repository
            vec = tf_idf[repo_name]["vectorizer"]

            # Get PR body from dataset
            body = ds.loc[i, "body"]

            # Check if body is valid
            if not body or not body.strip():
                print(f"Empty body for PR {pr_num} in {repo_name}")
                ds.loc[i, 'score'] = -1.0
                pass_uid = ds.loc[i, "uid"]
                continue

            # Vectorize the PR body
            try:
                body_vec = vec.transform([body])
            except Exception as vec_error:
                print(f"Error vectorizing body for {repo_name}: {vec_error}")
                ds.loc[i, 'score'] = -1.0
                pass_uid = ds.loc[i, "uid"]
                continue

        doc_url = ds.loc[i, "link"]

        try:
            # Get document content
            doc = ds.loc[i, "doc"]

            if not doc or not doc.strip():
                ds.loc[i, 'score'] = -1.0
                continue

            # Vectorize document
            doc_vec = vec.transform([doc])

            # Calculate cosine similarity
            score = cosine_similarity(body_vec, doc_vec)[0][0]
            ds.loc[i, 'score'] = score

        except Exception as doc_error:
            print(f"Error processing document for {doc_url}: {doc_error}")
            ds.loc[i, 'score'] = -1.0

    except Exception as main_error:
        print(f"Error processing row {i}: {main_error}")
        ds.loc[i, 'score'] = -1.0

    pass_uid = ds.loc[i, "uid"]

# Re-rank based on scores
ds['rerank'] = (
    ds
    .groupby("pr_link")['score']
    .rank(method="first", ascending=False)
    .astype("Int64")
)

# Save results
out = f"drive/MyDrive/monnetal/lastEval/tf_idfv2.csv"
ds.to_csv(out, index=False)
print(f"Saved new evaluation to {out}")

# Print statistics
valid_scores = ds[ds['score'] != -1.0]['score']
print(f"Processed {len(ds)} rows")
print(f"Valid scores: {len(valid_scores)} ({len(valid_scores)/len(ds)*100:.1f}%)")
print(f"Score statistics: min={valid_scores.min():.3f}, max={valid_scores.max():.3f}, mean={valid_scores.mean():.3f}")

Starting re-ranking with vectorizers for 18 repositories...

Re-ranking PR links:   0%|          | 0/356 [00:00<?, ?it/s]

Saved new evaluation to drive/MyDrive/monnetal/lastEval/tf_idfv2.csv
Processed 356 rows
Valid scores: 348 (97.8%)
Score statistics: min=0.000, max=1.000, mean=0.227

In [ ]:
# @title

pass_uid = None
pr_num = None
repo = None
pr = None
body = None
body_vec = None
vec = None

for i in notebook_tqdm.tqdm(ds.index, desc="Re-ranking PR links"):

    repo_name = ds.loc[i, "repo"]
    pr_link = ds.loc[i, "pr_link"]

    try:
        if pass_uid != ds.loc[i, "uid"]:
            pr_num = int(GITHUB_LINK_PATTERN.search(pr_link).group("pr"))
            # repo = g.get_repo(repo_name)
            # pr = repo.get_pull(pr_num)
            vec = tf_idf[repo_list.tolist().index(repo_name)]["vectorizer"]
            # body = pr.body or ""
            body = ds.loc[i, "body"]
            body_vec = vec.transform([body])

        doc_url = ds.loc[i, "link"]

        try:
            # doc = scrap(doc_url)
            doc = ds.loc[i, "doc"]
            doc_vec = vec.transform([doc])
            score = cosine_similarity(body_vec, doc_vec)[0][0]

            ds.loc[i, 'score'] = score

        except Exception:
            ds.loc[i, 'score'] = -1.0

    except Exception:
        ds.loc[i, 'score'] = -1.0

    pass_uid = ds.loc[i, "uid"]



ds['rerank'] = (
    ds
    .groupby("pr_link")['score']
    .rank(method="first", ascending=False)
    .astype("Int64")
)

out  = f"drive/MyDrive/monnetal/tf_idfv2.csv"

ds.to_csv(out, index=False)
print(f"Saved new evaluation to {out}")

In [ ]:
from sklearn.metrics import ndcg_score
from scipy.stats import kendalltau
from torchmetrics.retrieval import RetrievalMRR
from torchmetrics.functional import precision
import torch
def prec_at_k(group,k=1):
    preds = torch.tensor(group["rerank"].values.reshape(1, -1))
    target = torch.tensor(group["rank"].values.reshape(1, -1))

    return precision(preds, target,task = "multiclass", num_classes = int(group.shape[0]) , top_k = k)


def calculate_ndcg(group):
    if len(group) < 2:
        return None

    return ndcg_score(group['rank'].values.reshape(1, -1), group['rerank'].values.reshape(1, -1), k=10)


def compute_ndcg(df):
  all_ndcgs = df.groupby('pr_link').apply(calculate_ndcg)
  NDCG = all_ndcgs.mean()
  return NDCG

def compute_prec1(df):
  all_prec = df.groupby('pr_link').apply(prec_at_k)
  PREC = all_prec.mean()
  return PREC


def compute_mrr(df):
    mrrs = []

    for _, g in df.groupby('uid'):
        if len(g) < 1:
            continue

        y_true = g['rank'].values
        y_pred = g['score'].values

        order = np.argsort(-y_pred)
        y_true_sorted = y_true[order]

        max_rel = np.min(y_true_sorted)

        found = False
        for i, rel in enumerate(y_true_sorted):
            if rel == max_rel:
                mrrs.append(1.0 / (i + 1))
                found = True
                break

        if not found:
            mrrs.append(0.0)

    return np.mean(mrrs) if mrrs else 0.0

def compute_kendal(df):

  new_df = df.copy()
  new_df = new_df.dropna(subset=['rank', 'rerank'])

  correlations = []
  for pr_link, group in new_df.groupby('pr_link'):

        if len(group) > 1:
            tau, p_value = kendalltau(group['rank'].values, group['rerank'].values)
            if not np.isnan(tau):
                correlations.append(tau)

  avg_corr = np.mean(correlations)
  return avg_corr

In [ ]:
ds.dropna(subset=['uid'], inplace=True)

In [ ]:
dest = "lastEval"
evals = Path(f"drive/MyDrive/monnetal/{dest}")
filenames = [f.name for f in evals.iterdir() if f.is_file()]
modset = []
for filename in filenames:
  df = pd.read_csv(f"drive/MyDrive/monnetal/{dest}/"+filename)
  df.dropna(subset=['uid'], inplace=True)
  modset.append(df)
  print(f"{filename} loaded {df['score'].isna().sum()} {len(df)}")

all_minilm_l6_v2.csv loaded 0 356
jina_reranker.csv loaded 0 356
deepseek_coder.csv loaded 0 356
Mistral7B.csv loaded 0 356
ChatGPT.csv loaded 0 1560
LGBM8f.csv loaded 0 356
LGBM4f.csv loaded 0 356
LGBM19f.csv loaded 0 356
xgb4f.csv loaded 0 356
tf_idfv2.csv loaded 0 356
xgb19f.csv loaded 0 356
xgb8f.csv loaded 0 356
10foldx.csv loaded 0 356

In [ ]:
# @title
#convert chatgpt result
chatds = pd.read_csv("drive/MyDrive/monnetal/eval/chatGPT.csv")
def normalize_chatds_pr_link(pr_link_str):
    parts = pr_link_str.split('_pull_')
    repo_part = parts[0].replace('_', '/', 1)
    pr_number = parts[1]
    return f"https://github.com/{repo_part}/pull/{pr_number}"

chatds_normalized_pr_link = chatds.copy()
chatds_normalized_pr_link['pr_link_normalized'] = chatds_normalized_pr_link['pr_link'].apply(normalize_chatds_pr_link)

gpteval = pd.merge(
    ds,
    chatds_normalized_pr_link,
    left_on='pr_link',
    right_on='pr_link_normalized',
    how='inner'
)


# print(gpteval.head())
#

gpteval = gpteval.rename(columns={'rank_y': 'rank', 'rerank_y': 'rerank','link_count_y':'link_count'})
calculated_score = gpteval.groupby('uid')['rerank'].transform(lambda x: x.max() - x + 1)
gpteval['score'] = calculated_score
gpteval.loc[gpteval['score'] == 1002, 'score'] = -999
exceed10 = gpteval[gpteval['link_count'] > 10]['uid'].unique()
uids_to_cap = gpteval[gpteval['uid'].isin(exceed10)]
uids_to_keep = gpteval[~gpteval['uid'].isin(exceed10)]

capped_uids = uids_to_cap.groupby('uid').head(10)

gpteval = pd.concat([capped_uids, uids_to_keep]).sort_values(by=['uid']).reset_index(drop=True)

gpteval.to_csv("drive/MyDrive/monnetal/lastEval/ChatGPT.csv", index=False)

NameError: name 'ds' is not defined

In [ ]:
NDCG10 = []
for i in range(len(modset)):
  modset[i]['score'] = modset[i]['score'].apply(extract_score_to_float)
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
  NDCG = all_ndcgs.mean()
  NDCG10.append(f"{filenames[i]}: ndcg@10 = {NDCG:.3f}")
prec1= []
for i in range(len(modset)):
  try:
    all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
  except Exception:
    print(f"on {filenames[i]} Dataset validation:")
    print(f"Unique UIDs: {modset[i]['uid'].nunique()}")
    # print(f"Missing link count: {modset[i]['link_count'].isna().sum()}")
    # print(f"Missing link count: {modset[i]['link_count'].isna().sum()}")
  PREC = all_prec.mean()
  prec1.append(f"{filenames[i]}: prec@10 = {PREC:.3f}")
mrr = []
for i in range(len(modset)):
  modset[i]['score'] = modset[i]['score'].apply(extract_score_to_float)
  modset[i]['score'] = modset[i]['score'].astype(float)
  mrr.append(f"{filenames[i]}: mrr = {compute_mrr(modset[i]):.3f}")
from scipy.stats import kendalltau

kendal = []
for i in range(len(modset)):
    new_df = modset[i].copy()

    new_df = new_df.dropna(subset=['rank', 'rerank'])

    correlations = []
    for pr_link, group in new_df.groupby('uid'):

        if len(group) > 1:
            tau, p_value = kendalltau(group['rank'].values, group['rerank'].values)
            if not np.isnan(tau):
                correlations.append(tau)

    if correlations:
        avg_corr = np.mean(correlations)
        kendal.append(f"{filenames[i]}: Kendall tau = {avg_corr:.3f}")
    else:
        kendal.append(f"{filenames[i]}: Kendall tau = NaN (no valid correlations)")

/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_ndcgs = modset[i].groupby('uid').apply(calculate_ndcg)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)

on ChatGPT.csv Dataset validation:
Unique UIDs: 68

/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)
/tmp/ipykernel_2150/2284642788.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  all_prec = modset[i].groupby('pr_link').apply(prec_at_k)

In [ ]:
mrr

['all_minilm_l6_v2.csv: mrr = 0.756',
 'jina_reranker.csv: mrr = 0.656',
 'deepseek_coder.csv: mrr = 0.692',
 'Mistral7B.csv: mrr = 0.720',
 'ChatGPT.csv: mrr = 0.464',
 'LGBM8f.csv: mrr = 0.752',
 'LGBM4f.csv: mrr = 0.606',
 'LGBM19f.csv: mrr = 0.520',
 'xgb4f.csv: mrr = 0.606',
 'tf_idfv2.csv: mrr = 0.700',
 'xgb19f.csv: mrr = 0.641',
 'xgb8f.csv: mrr = 0.641',
 '10foldx.csv: mrr = 0.551']

In [ ]:
NDCG10

['all_minilm_l6_v2.csv: ndcg@10 = 0.931',
 'jina_reranker.csv: ndcg@10 = 0.937',
 'deepseek_coder.csv: ndcg@10 = 0.918',
 'Mistral7B.csv: ndcg@10 = 0.934',
 'ChatGPT.csv: ndcg@10 = 0.777',
 'LGBM8f.csv: ndcg@10 = 0.956',
 'LGBM4f.csv: ndcg@10 = 0.919',
 'LGBM19f.csv: ndcg@10 = 0.919',
 'xgb4f.csv: ndcg@10 = 0.919',
 'tf_idfv2.csv: ndcg@10 = 0.918',
 'xgb19f.csv: ndcg@10 = 0.946',
 'xgb8f.csv: ndcg@10 = 0.946',
 '10foldx.csv: ndcg@10 = 0.924']

In [ ]:
prec1

['all_minilm_l6_v2.csv: prec@10 = 0.384',
 'jina_reranker.csv: prec@10 = 0.501',
 'deepseek_coder.csv: prec@10 = 0.352',
 'Mistral7B.csv: prec@10 = 0.392',
 'ChatGPT.csv: prec@10 = 0.392',
 'LGBM8f.csv: prec@10 = 0.585',
 'LGBM4f.csv: prec@10 = 0.451',
 'LGBM19f.csv: prec@10 = 0.380',
 'xgb4f.csv: prec@10 = 0.451',
 'tf_idfv2.csv: prec@10 = 0.389',
 'xgb19f.csv: prec@10 = 0.487',
 'xgb8f.csv: prec@10 = 0.487',
 '10foldx.csv: prec@10 = 0.383']

In [ ]:
kendal

['all_minilm_l6_v2.csv: Kendall tau = 0.429',
 'jina_reranker.csv: Kendall tau = 0.469',
 'deepseek_coder.csv: Kendall tau = 0.361',
 'Mistral7B.csv: Kendall tau = 0.429',
 'ChatGPT.csv: Kendall tau = 0.073',
 'LGBM8f.csv: Kendall tau = 0.632',
 'LGBM4f.csv: Kendall tau = 0.336',
 'LGBM19f.csv: Kendall tau = 0.322',
 'xgb4f.csv: Kendall tau = 0.336',
 'tf_idfv2.csv: Kendall tau = 0.354',
 'xgb19f.csv: Kendall tau = 0.532',
 'xgb8f.csv: Kendall tau = 0.532',
 '10foldx.csv: Kendall tau = 0.321']